import type { NextPage } from "next";
import Head from "next/head";
import Landing from "../layout/landing";
import About from "../layout/about";
import Work from "../layout/work";
import Projects from "../layout/projects";
import Socials from "../components/socials";
import { mobileWidth } from "../utils/variables";
import { WindowContext } from "../components/resizer";
import { useContext } from "react";

const Home: NextPage = () => {
  const windowWidth = useContext(WindowContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main>
        <Landing />
        <About />
        <Work />
        <Projects />
        {windowWidth > mobileWidth && <Socials />}
      </main>
    </>
  );
};

export default Home;
